name:                advent-of-code
version:             0.1.0.0
github:              "droopert/advent-of-code-2020"
license:             BSD3
author:              "droobertzka"
maintainer:          "example@example.com"
copyright:           "2020 droobertzka"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/droopert/advent-of-code-2020#readme>

dependencies:
- base >= 4.7 && < 5
- split == 0.2.3.4
- text >= 1.2.4.0 && < 5
- containers >= 0.6.2.1 && < 9

library:
  source-dirs: src

executables:
  advent-of-code-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - advent-of-code
